default_challenge: recaptcha/reCAPTCHA
description: 'Esta questão é para testar se você é um visitante humano ou não  a fim de prevenir submissões automáticas de spam.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 0
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
langcode: pt-pt
