definitions:
  standard__front_page:
    weight: -50
    menu_name: main-menu
    parent: ''
    enabled: true
    expanded: false
  contact__site_page:
    weight: -41
    menu_name: main-menu
    parent: ''
    enabled: true
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: pt-pt
