features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://drupal-logo (1)_0_0.jpg'
favicon:
  use_default: 1
  path: ''
