export:
  folder: custom
langcode: pt-pt
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
popup_info:
  value: "<h2>We use cookies on this site to enhance your user experience</h2>\r\n\r\n<p>By clicking any link on this page you are giving your consent for us to set cookies.</p>\r\n"
  format: full_html
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: full_html
_core:
  default_config_hash: 1nGjaIrY9azKyikRoo0FTLRRSILozzYtUExZ4sLK_0E
domain: ''
popup_enabled: true
popup_clicking_confirmation: true
popup_position: true
popup_agree_button_message: 'OK, I agree'
popup_disagree_button_message: 'No, give me more info'
popup_agreed_enabled: true
popup_hide_agreed: false
popup_find_more_button_message: 'More info'
popup_hide_button_message: Esconder
popup_link: 'https://www.drupal.pt/contact'
popup_link_new_window: true
popup_height: null
popup_width: '100'
popup_delay: 1
popup_bg_hex: 0779BF
popup_text_hex: ffffff
domains_option: 1
domains_list: "http://dev.drupal.pt\r\nhttp://stg.drupal.pt\r\nhttp://www.drupal.pt\r\nhttp://drupal.pt\r\nhttp://dev.drupal-pt.org\r\nhttp://stg.drupal-pt.org\r\nhttp://www.drupal-pt.org\r\nhttp://drupal-pt.org\r\nhttp://druportugaldev.prod.acquia-sites.com\r\nhttp://druportugalstg.prod.acquia-sites.com\r\nhttp://druportugal.prod.acquia-sites.com"
