cookie_lifetime: 100
domain: ''
domains_option: 1
domains_list: ''
eu_only: null
eu_only_js: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: false
langcode: pt-pt
popup_agreed:
  value: '<h2>Obrigado por aceitar os cookies.</h2><p>Pode esconder esta mensagem ou saber mais sobre a nossa política de cookies.</p>'
  format: restricted_html
popup_agree_button_message: Concordo
popup_agreed_enabled: false
popup_bg_hex: 1A1A1A
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
popup_delay: 1000
popup_enabled: true
popup_find_more_button_message: 'Mais informação'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Ocultar
popup_info:
  value: '<h2>Usamos cookies para permitir uma melhor experiência.</h2><p>Ao navegar no site estará a consentir a sua utilização.</p>'
  format: restricted_html
mobile_popup_info:
  value: ''
  format: markdown
popup_info_template: new
mobile_breakpoint: 768
popup_link: '<front>'
popup_link_new_window: true
popup_position: false
fixed_top_position: true
popup_text_hex: ffffff
popup_width: 100%
use_bare_css: false
disagree_do_not_show_popup: false
reload_page: false
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: false
method: opt_in
disagree_button_label: 'Não concordo'
disabled_javascripts: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>Usamos cookies para permitir uma melhor experiência</h2><p>Deu-nos consentimento para definir cookies.</p>'
  format: restricted_html
withdraw_action_button_label: 'Retirar consentimento'
withdraw_tab_button_label: 'Politica de privacidade'
withdraw_enabled: false
_core:
  default_config_hash: 9RpVluEdsYtiE1Ity_X-P_3WmflzyJFit3v3u5k_w8c
cookie_session: 0
enable_save_preferences_button: true
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
withdraw_button_on_info_popup: false
domain_all_sites: false
uuid: 6b78040c-89f2-423a-9175-d0d71e2c0500
show_more_info: true
popup_more_info_button_message: 'Mais informação'
reload_options: 0
reload_routes_list: ''
containing_element: body
settings_tab_enabled: false
automatic_cookies_removal: true
set_cookie_session_zero_on_disagree: 0
cookie_policy_version: 1.0.0
allowed_cookies: ''
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
