label: 'Gender identity'
description: 'Your <a href="http://www.telegraph.co.uk/men/the-filter/a-nearly-complete-glossary-of-gender-identities-for-your-next-ce/">gender identity</a>, ie, how you identity yourself with your own gender. This information will be <strong>private</strong>.'
