settings:
  allowed_values:
    -
      label: Bigender
    -
      label: Feminine
    -
      label: 'Gender fluid'
    -
      label: 'Gender neutral'
    -
      label: 'Gender queer'
    -
      label: Masculine
    -
      label: Transgender
    -
      label: 'Rather not say'
