display:
  default:
    display_options:
      title: Master
      exposed_form:
        options:
          submit_button: Applu
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area:
          content:
            value: 'No results were found.'
            format: markdown
  block_created:
    display_title: Created
    display_options:
      title: Created
  block_user_picture:
    display_title: Picture
    display_options:
      title: Picture
