display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      title: 'Associate Directory'
      header:
        result:
          content: 'Displaying @start - @end of @total'
      empty:
        area:
          content:
            value: 'No results were found.'
            format: plain_text
  page_associate:
    display_options:
      menu:
        title: 'Associate Directory'
  page_collective:
    display_options:
      menu:
        title: 'Collective Associate Directory'
      title: 'Collective Associate Directory'
  page_individual:
    display_options:
      menu:
        title: 'Individual Associate Directory'
      title: 'Individual Associate Directory'
