display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      title: 'Associate Directory'
      header:
        result:
          content: 'Displaying @start - @end of @total'
      empty:
        area:
          content:
            value: 'No results were found.'
            format: plain_text
      filters:
        name:
          expose:
            label: 'User name'
        field_profile_name_fullname:
          expose:
            label: 'Full name'
        field_profile_list_genderident_value:
          expose:
            label: 'Gender identity'
        field_profile_lang_languages_value:
          expose:
            label: Language
        field_profile_address_postal_country_code:
          expose:
            label: Country
        field_profile_address_postal_locality:
          expose:
            label: City
  page_associate:
    display_options:
      menu:
        title: 'Associate Directory'
