description: 'A tua <a href="http://www.telegraph.co.uk/men/the-filter/a-nearly-complete-glossary-of-gender-identities-for-your-next-ce/">identidade de género</a>, isto é, como te identificas com o teu género. Esta informação será <strong>privada</strong>.'
label: 'Identidade de género'
