label: 'Número de Identificação de Pessoa Coletiva (NIPC)'
description: 'O Número de Identificação de Pessoa Coletiva do Associado Coletivo, ex, organização. Esta informação será <strong>privada</strong>.'
