display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        sid:
          label: '#'
          separator: ', '
        in_draft:
          label: Rascunho
          separator: ', '
        created:
          label: Criado
          separator: ', '
        remote_addr:
          label: 'Endereço IP'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: ver
      arguments:
        in_draft:
          exception:
            title: Todos
  embed_administer:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        sid:
          label: '#'
          separator: ', '
        in_draft:
          label: Rascunho
          separator: ', '
        sticky:
          label: 'Em destaque'
          separator: ', '
        locked:
          label: Bloqueado
          separator: ', '
        created:
          label: Criado
          separator: ', '
        completed:
          label: Concluída
          separator: ', '
        remote_addr:
          label: 'Endereço IP'
          separator: ', '
        operations:
          label: Operations
      filters:
        sticky:
          expose:
            label: 'Em destaque'
        locked:
          expose:
            label: Bloqueado
  embed_manage:
    display_options:
      fields:
        webform_submission_bulk_form:
          action_title: Action
        sid:
          label: '#'
          separator: ', '
        in_draft:
          label: Rascunho
          separator: ', '
        sticky:
          label: 'Em destaque'
          separator: ', '
        locked:
          label: Bloqueado
          separator: ', '
        created:
          label: Criado
          separator: ', '
        completed:
          label: Concluída
          separator: ', '
        remote_addr:
          label: 'Endereço IP'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: ver
        edit_webform_submission:
          label: Operations
          text: editar
      filters:
        sticky:
          expose:
            label: 'Em destaque'
        locked:
          expose:
            label: Bloqueado
  embed_review:
    display_options:
      fields:
        sid:
          label: '#'
          separator: ', '
        in_draft:
          label: Rascunho
          separator: ', '
        sticky:
          label: 'Em destaque'
          separator: ', '
        locked:
          label: Bloqueado
          separator: ', '
        created:
          label: Criado
          separator: ', '
        completed:
          label: Concluída
          separator: ', '
        remote_addr:
          label: 'Endereço IP'
          separator: ', '
        view_webform_submission:
          label: Operations
          text: ver
      filters:
        sticky:
          expose:
            label: 'Em destaque'
        locked:
          expose:
            label: Bloqueado
