label: Pessoas
description: 'Encontrar e gerir pessoas a interagir com o seu site.'
display:
  default:
    display_title: Principal
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            next: 'Seguinte ›'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      fields:
        user_bulk_form:
          label: 'Atualização em massa'
        name:
          label: Utilizador
        status:
          label: Estado
        roles_target_id:
          label: 'Grupos de utilizador'
        created:
          label: 'Membro desde'
        access:
          label: 'Último acesso'
        operations:
          label: Operações
      filters:
        roles_target_id:
          expose:
            label: Grupo
        permission:
          expose:
            label: Permissão
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Ativo
                value: '1'
              2:
                title: Bloqueado
      title: Pessoas
      empty:
        area_text_custom:
          content: 'Nenhuma pessoa disponível.'
      use_more_text: mais
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Lista
        description: 'Encontrar e gerir pessoas a interagir com o seu site.'
      tab_options:
        title: Pessoas
        description: 'Gerir contas de utilizadores, grupos e permissões.'
