display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            previous: '‹‹ Anterior'
            next: 'Próximo ››'
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      title: Eventos
      use_more_text: mais
  block_events:
    display_options:
      use_more_text: mais
      block_description: Eventos
  page_events:
    display_options:
      menu:
        title: Eventos
