display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            previous: '‹‹ Anterior'
            next: 'Próximo ››'
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Ites por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      title: Notícias
  block_news:
    display_options:
      block_description: Notícias
      use_more_text: mais
  page_news:
    display_options:
      menu:
        title: Notícias
