display:
  default:
    display_options:
      pager:
        options:
          tags:
            previous: '‹‹ Anterior'
            next: 'Próxima ››'
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      title: 'Diretório de Membros'
      header:
        result:
          content: 'Mostrando @start - @end de @total'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      empty:
        area:
          content:
            value: 'Nenhuns resultados foram encontrados.'
            format: markdown
  page_directory:
    display_options:
      menu:
        title: 'Diretório de Membros'
