display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordernar por'
          sort_asc_label: Ascendente
          sort_desc_label: Descendente
      pager:
        options:
          tags:
            previous: '‹‹ Anterior'
            next: 'Próximo ››'
            first: '« Primeiro'
            last: 'Último »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      title: 'Diretório de Associados'
      header:
        result:
          content: 'Mostrando @start - @end de @total'
      empty:
        area:
          content:
            value: 'Nenhuns resultados foram encontrados.'
            format: markdown
  page_associate:
    display_options:
      menu:
        title: 'Diretório de Associados'
  page_collective:
    display_options:
      menu:
        title: 'Diretório de Associados Coletivos'
      title: 'Diretório de Associados Coletivos'
  page_individual:
    display_options:
      menu:
        title: 'Diretório de Associados Individuais'
      title: 'Diretório de Associados Individuais'
